name: NPM Release

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.45.0-jammy

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: "npm"
          registry-url: https://registry.npmjs.org/

      - name: Cache dependencies
        id: modules-cache
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

      - run: npm ci
        if: steps.modules-cache.outputs.cache-hit != 'true'

      - run: npm run build

      - run: npm run release:npm
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
